# Generated by Django 3.1 on 2022-11-09 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('endereço', models.CharField(max_length=300)),
                ('descrição', models.CharField(max_length=250)),
                ('coordX', models.FloatField()),
                ('coordY', models.FloatField()),
                ('foto', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
