# Generated by Django 3.1 on 2023-01-09 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150)),
                ('endereço', models.CharField(max_length=300)),
                ('descriçao', models.CharField(max_length=350)),
                ('ponto_ref', models.CharField(max_length=400, null=True)),
                ('coordX', models.FloatField()),
                ('coordY', models.FloatField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('state', models.CharField(choices=[('pendente', 'Pendente'), ('resgatado', 'Resgatado'), ('naolocalizado', 'Não localizado')], default='pendente', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
