# Generated by Django 3.1 on 2022-11-10 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='descrição',
            new_name='descriçao',
        ),
    ]
