# Generated by Django 3.1 on 2022-11-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0003_auto_20221122_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
