# Generated by Django 3.1 on 2022-11-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0004_auto_20221122_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='foto',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
