# Generated by Django 3.1 on 2022-11-29 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('animais', '0006_auto_20221129_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='ponto_ref',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='user',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animal',
            name='descriçao',
            field=models.CharField(max_length=350),
        ),
    ]
