# Generated by Django 3.1 on 2022-12-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0008_auto_20221229_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='estado',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('resgatado', 'Resgatado'), ('naolocalizado', 'Não localizado')], default='pendente', max_length=50),
        ),
    ]
